CREATE EXTENSION IF NOT EXISTS vector;
CREATE TABLE IF NOT EXISTS schema_version (version integer PRIMARY KEY);
INSERT INTO schema_version VALUES (1) ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS datasets (
    id text PRIMARY KEY, equipment text NOT NULL DEFAULT 'M-01'
);
CREATE TABLE IF NOT EXISTS measurements (
    dataset text NOT NULL REFERENCES datasets(id), sensor text NOT NULL,
    timestamp timestamptz NOT NULL, value double precision NOT NULL,
    PRIMARY KEY (dataset, sensor, timestamp),
    CHECK (sensor IN ('temperature', 'speed')),
    CHECK (value > '-Infinity'::float8 AND value < 'Infinity'::float8)
);
CREATE TABLE IF NOT EXISTS investigations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL, scenario text NOT NULL,
    alert_time timestamptz NOT NULL, payload jsonb NOT NULL
);
CREATE TABLE IF NOT EXISTS imports (
    fingerprint text PRIMARY KEY, source text NOT NULL,
    imported_at timestamptz NOT NULL DEFAULT now(), summary jsonb NOT NULL
);
CREATE TABLE IF NOT EXISTS corpus_generations (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    active boolean NOT NULL DEFAULT false, manifest jsonb NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS one_active_corpus ON corpus_generations(active) WHERE active;
CREATE TABLE IF NOT EXISTS passages (
    generation bigint NOT NULL REFERENCES corpus_generations(id),
    id text NOT NULL, document text NOT NULL, title text NOT NULL,
    section text NOT NULL, text text NOT NULL, version text NOT NULL,
    equipment text NOT NULL, revision integer NOT NULL,
    valid_from timestamptz NOT NULL, valid_to timestamptz,
    embedding vector(384) NOT NULL,
    PRIMARY KEY (generation, id),
    CHECK (valid_to IS NULL OR valid_to > valid_from)
);
CREATE TABLE IF NOT EXISTS evaluation_runs (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(), kind text NOT NULL,
    status text NOT NULL DEFAULT 'running', config jsonb NOT NULL
);
CREATE TABLE IF NOT EXISTS evaluation_results (
    run_id bigint NOT NULL REFERENCES evaluation_runs(id),
    case_id text NOT NULL, mode text NOT NULL, attempt integer NOT NULL DEFAULT 1,
    result jsonb NOT NULL, review jsonb,
    PRIMARY KEY (run_id, case_id, mode, attempt)
);
